version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:4000
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
